import {
  Ban,
  Bot,
  Braces,
  Bug,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlus,
  CircleSlash,
  CircleX,
  ClipboardCheck,
  CloudCheck,
  Code,
  CodeXml,
  CreditCard,
  Database,
  Diff,
  Download,
  FileText,
  FileType2,
  Flag,
  FlaskConical,
  Folder,
  FolderOpen,
  Gauge,
  Gavel,
  GitCommitHorizontal,
  GitMerge,
  Hand,
  HeartPulse,
  Image,
  Info,
  LayoutGrid,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  type LucideIcon,
  Megaphone,
  MemoryStick,
  Merge,
  MessageSquareText,
  MessagesSquare,
  Newspaper,
  NotebookPen,
  OctagonAlert,
  Paperclip,
  PiggyBank,
  Pin,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Route,
  Ruler,
  Save,
  Scale,
  Send,
  Server,
  Settings,
  Shield,
  ShieldUser,
  SlidersHorizontal,
  Split,
  SquareKanban,
  TextSearch,
  ThumbsUp,
  Ticket,
  TimerOff,
  TrendingDown,
  TrendingUp,
  UserCheck,
  Vote,
  Waypoints,
  Workflow,
  Zap,
} from 'lucide-react';

// The design (and its fixtures) name icons in Material Symbols vocabulary;
// the stack renders lucide. One mapping, kept where both sides can see it.
const designIcons: Record<string, LucideIcon> = {
  sync: RefreshCw,
  bolt: Zap,
  front_hand: Hand,
  hub: Waypoints,
  error: CircleAlert,
  rate_review: MessageSquareText,
  description: FileText,
  trending_up: TrendingUp,
  article: Newspaper,
  merge_type: GitMerge,
  database: Database,
  folder: Folder,
  memory: MemoryStick,
  credit_card: CreditCard,
  bug_report: Bug,
  campaign: Megaphone,
  image: Image,
  account_tree: Workflow,
  difference: Diff,
  fact_check: ClipboardCheck,
  savings: PiggyBank,
  speed: Gauge,
  folder_open: FolderOpen,
  settings: Settings,
  check_circle: CircleCheck,
  call_split: Split,
  call_merge: Merge,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  alt_route: Route,
  pause_circle: CirclePause,
  flag: Flag,
  confirmation_number: Ticket,
  smart_toy: Bot,
  receipt_long: ReceiptText,
  gavel: Gavel,
  how_to_vote: Vote,
  thumb_up: ThumbsUp,
  edit_note: NotebookPen,
  keep: Pin,
  send: Send,
  shield_person: ShieldUser,
  block: Ban,
  info: Info,
  merge: Merge,
  change_circle: CircleDot,
  add_circle: CirclePlus,
  remove_circle: CircleMinus,
  commit: GitCommitHorizontal,
  download: Download,
  summarize: FileText,
  data_object: Braces,
  html: CodeXml,
  cancel: CircleX,
  lock: Lock,
  trending_down: TrendingDown,
  payments: CircleDollarSign,
  save: Save,
  do_not_disturb_on: CircleSlash,
  how_to_reg: UserCheck,
  tune: SlidersHorizontal,
  cloud_done: CloudCheck,
  dns: Server,
  replay: RotateCcw,
  timer_off: TimerOff,
  code: Code,
  science: FlaskConical,
  route: Route,
  manage_search: TextSearch,
  link: Link,
  picture_as_pdf: FileType2,
  rule: ListChecks,
  forum: MessagesSquare,
  help: CircleHelp,
  monitor_heart: HeartPulse,
  view_kanban: SquareKanban,
  straighten: Ruler,
  shield: Shield,
  lightbulb: Lightbulb,
  attach_file: Paperclip,
  workspaces: LayoutGrid,
  report: OctagonAlert,
  balance: Scale,
};

export function designIcon(name: string): LucideIcon {
  return designIcons[name] ?? Circle;
}
