import {
  Bot,
  Bug,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CirclePause,
  ClipboardCheck,
  CreditCard,
  Database,
  Diff,
  FileText,
  Flag,
  Folder,
  FolderOpen,
  Gauge,
  GitMerge,
  Hand,
  Image,
  type LucideIcon,
  Megaphone,
  MemoryStick,
  Merge,
  MessageSquareText,
  Newspaper,
  PiggyBank,
  ReceiptText,
  RefreshCw,
  Route,
  Settings,
  Split,
  Ticket,
  TrendingUp,
  Waypoints,
  Workflow,
  Zap,
} from 'lucide-react';

// The design (and its fixtures) name icons in Material Symbols vocabulary;
// the stack renders lucide. One mapping, kept where both sides can see it.
const designIcons: Record<string, LucideIcon> = {
  sync: RefreshCw,
  bolt: Zap,
  front_hand: Hand,
  hub: Waypoints,
  error: CircleAlert,
  rate_review: MessageSquareText,
  description: FileText,
  trending_up: TrendingUp,
  article: Newspaper,
  merge_type: GitMerge,
  database: Database,
  folder: Folder,
  memory: MemoryStick,
  credit_card: CreditCard,
  bug_report: Bug,
  campaign: Megaphone,
  image: Image,
  account_tree: Workflow,
  difference: Diff,
  fact_check: ClipboardCheck,
  savings: PiggyBank,
  speed: Gauge,
  folder_open: FolderOpen,
  settings: Settings,
  check_circle: CircleCheck,
  call_split: Split,
  call_merge: Merge,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  alt_route: Route,
  pause_circle: CirclePause,
  flag: Flag,
  confirmation_number: Ticket,
  smart_toy: Bot,
  receipt_long: ReceiptText,
};

export function designIcon(name: string): LucideIcon {
  return designIcons[name] ?? Circle;
}
