/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as NewJobRouteImport } from './routes/new-job'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceBuildRouteImport } from './routes/workspace/build'
import { Route as WorkspacePlanRouteImport } from './routes/workspace/plan'
import { Route as WorkspaceRunRouteImport } from './routes/workspace/run'
import { Route as WorkspaceValidateRouteImport } from './routes/workspace/validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const NewJobRoute = NewJobRouteImport.update({
  id: '/new-job',
  path: '/new-job',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceBuildRoute = WorkspaceBuildRouteImport.update({
  id: '/workspace/build',
  path: '/workspace/build',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacePlanRoute = WorkspacePlanRouteImport.update({
  id: '/workspace/plan',
  path: '/workspace/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRunRoute = WorkspaceRunRouteImport.update({
  id: '/workspace/run',
  path: '/workspace/run',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceValidateRoute = WorkspaceValidateRouteImport.update({
  id: '/workspace/validate',
  path: '/workspace/validate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/jobs': typeof JobsRoute
  '/manage': typeof ManageRoute
  '/new-job': typeof NewJobRoute
  '/settings': typeof SettingsRoute
  '/workspace/build': typeof WorkspaceBuildRoute
  '/workspace/plan': typeof WorkspacePlanRoute
  '/workspace/run': typeof WorkspaceRunRoute
  '/workspace/validate': typeof WorkspaceValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/jobs': typeof JobsRoute
  '/manage': typeof ManageRoute
  '/new-job': typeof NewJobRoute
  '/settings': typeof SettingsRoute
  '/workspace/build': typeof WorkspaceBuildRoute
  '/workspace/plan': typeof WorkspacePlanRoute
  '/workspace/run': typeof WorkspaceRunRoute
  '/workspace/validate': typeof WorkspaceValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/jobs': typeof JobsRoute
  '/manage': typeof ManageRoute
  '/new-job': typeof NewJobRoute
  '/settings': typeof SettingsRoute
  '/workspace/build': typeof WorkspaceBuildRoute
  '/workspace/plan': typeof WorkspacePlanRoute
  '/workspace/run': typeof WorkspaceRunRoute
  '/workspace/validate': typeof WorkspaceValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/jobs'
    | '/manage'
    | '/new-job'
    | '/settings'
    | '/workspace/build'
    | '/workspace/plan'
    | '/workspace/run'
    | '/workspace/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/jobs'
    | '/manage'
    | '/new-job'
    | '/settings'
    | '/workspace/build'
    | '/workspace/plan'
    | '/workspace/run'
    | '/workspace/validate'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/jobs'
    | '/manage'
    | '/new-job'
    | '/settings'
    | '/workspace/build'
    | '/workspace/plan'
    | '/workspace/run'
    | '/workspace/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  JobsRoute: typeof JobsRoute
  ManageRoute: typeof ManageRoute
  NewJobRoute: typeof NewJobRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceBuildRoute: typeof WorkspaceBuildRoute
  WorkspacePlanRoute: typeof WorkspacePlanRoute
  WorkspaceRunRoute: typeof WorkspaceRunRoute
  WorkspaceValidateRoute: typeof WorkspaceValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-job': {
      id: '/new-job'
      path: '/new-job'
      fullPath: '/new-job'
      preLoaderRoute: typeof NewJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/build': {
      id: '/workspace/build'
      path: '/workspace/build'
      fullPath: '/workspace/build'
      preLoaderRoute: typeof WorkspaceBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/plan': {
      id: '/workspace/plan'
      path: '/workspace/plan'
      fullPath: '/workspace/plan'
      preLoaderRoute: typeof WorkspacePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/run': {
      id: '/workspace/run'
      path: '/workspace/run'
      fullPath: '/workspace/run'
      preLoaderRoute: typeof WorkspaceRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/validate': {
      id: '/workspace/validate'
      path: '/workspace/validate'
      fullPath: '/workspace/validate'
      preLoaderRoute: typeof WorkspaceValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  JobsRoute: JobsRoute,
  ManageRoute: ManageRoute,
  NewJobRoute: NewJobRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceBuildRoute: WorkspaceBuildRoute,
  WorkspacePlanRoute: WorkspacePlanRoute,
  WorkspaceRunRoute: WorkspaceRunRoute,
  WorkspaceValidateRoute: WorkspaceValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
